# Specifies the Docker Compose file format version. Version 3 is recommended.
version: '3.8'

# Defines the services (containers) that make up your app.
services:
  # The name of our service (can be anything).
  api:
    # Tells Docker Compose to build the image from the Dockerfile in the current directory.
    build: .
    # Sets the name for the container created from the image.
    container_name: fastapi_harness_app
    # Maps port 8080 on the host machine to port 80 in the container.
    # This matches the EXPOSE and CMD instructions in the Dockerfile.
    ports:
      - "8080:80"
    # Mounts the local './app' directory into the '/app/app' directory inside the container.
    # This enables live-reloading of your code. Any changes you make locally
    # will be immediately available in the running container without rebuilding.
    volumes:
      - ./app:/app/app
