# Kubernetes API version for Deployments
apiVersion: apps/v1
# Kind of object we are creating
kind: Deployment
metadata:
  # Name of the Deployment
  name: fastapi-harness-deployment
spec:
  # Number of replica Pods to run
  replicas: 2
  # Selector to identify which Pods to manage
  selector:
    matchLabels:
      app: fastapi-harness-app
  # Template for the Pods that will be created
  template:
    metadata:
      # Labels to apply to the Pods
      labels:
        app: fastapi-harness-app
    spec:
      # Definition of the containers running in the Pod
      containers:
      - name: fastapi-container
        # IMPORTANT: This image should be available to your Minikube cluster.
        image: dannykiselev/dannykiselev-repo:v1
        # The port that the container exposes. Updating for consistency.
        ports:
        - containerPort: 8080
---
# Separator for the next resource definition in the same file
# ---
# Kubernetes API version for Services
apiVersion: v1
# Kind of object we are creating
kind: Service
metadata:
  # Name of the Service
  name: fastapi-harness-service
spec:
  # Use NodePort to expose the service on a static port on each of the cluster's nodes.
  type: NodePort
  # Selector to identify which Pods will receive traffic from this service
  # This must match the labels on the Pods defined in the Deployment
  selector:
    app: fastapi-harness-app
  # Port mapping for the service
  ports:
    # The protocol for the port
  - protocol: TCP
    # The port on the service itself
    port: 80
    # THE FIX: Point to the port the application is ACTUALLY running on inside the container.
    targetPort: 8080
