pipeline:
  identifier: Build_fastapi_harness_sample_1749173463103
  name: Build fastapi-harness-sample
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: git
        repoName: fastapi-harness-sample
  stages:
    - stage:
        name: FastAPI CI
        identifier: FastAPI_CI
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Install Dependencies
                  identifier: Install_Dependencies
                  spec:
                    shell: Sh
                    command: sudo apt-get update && sudo apt-get install -y python3-dev && sudo apt-get install default-libmysqlclient-dev
              - step:
                  type: Run
                  name: pip install
                  identifier: pip
                  spec:
                    shell: Sh
                    command: |
                      python -m venv env-name
                      source env-name/bin/activate
                      pip install -r requirements.txt
                    connectorRef: account.harnessImage
                    image: alpine
                  timeout: 10m
              - step:
                  type: Test
                  name: Testing
                  identifier: Test_1
                  spec:
                    shell: Sh
                    command: "pytest "
                    intelligenceMode: true
              - step:
                  type: BuildAndPushDockerRegistry
                  name: Build and Push to DockerHub
                  identifier: Build_and_Push_to_DockerHub
                  spec:
                    connectorRef: account.DOCKE
                    repo: dannykiselev/dannykiselev-repo
                    tags:
                      - "1.0"
                    caching: true
            rollbackSteps: []
          caching:
            enabled: true
            paths: []
          buildIntelligence:
            enabled: true
        description: ""
  description: This pipeline was updated by Harness AI on 2025-06-06 19:43:30 UTC.
  tags:
    ai_generated: "true"
