pipeline:
  identifier: Build_fastapi_harness_sample_1749173463103
  name: Build fastapi-harness-sample
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: git
        repoName: fastapi-harness-sample
  stages:
    - stage:
        name: FastAPI CI
        identifier: FastAPI_CI
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Install Dependencies
                  identifier: Install_Dependencies
                  spec:
                    shell: Sh
                    command: |-
                      sudo apt-get update && sudo apt-get install -y python3-dev && sudo apt-get install default-libmysqlclient-dev
                      pip install --cache-dir .pip_cache -r requirements.txt
                    envVariables:
                      PIP_CACHE_DIR: /root/.cache
              - step:
                  type: Test
                  name: Test
                  identifier: Test_1
                  spec:
                    shell: Sh
                    command: pytest
                    intelligenceMode: false
          caching:
            enabled: true
            paths: []
          buildIntelligence:
            enabled: true
        description: ""
